server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/wp?useSSL=FALSE&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 88888888
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: wp
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-attempts: 210000
        multiplier: 2
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
mybatis:
  type-aliases-package: com.njucm.user.pojo